 - name: New Relic JUnit Reporter
  # You may pin to the exact commit or the version.
  # uses: newrelic/junit-reporter-action@a225f3d3753f08921149ddd803040fe593c4ad5c
   uses: newrelic/junit-reporter-action@v0.3.0
     with:
       # Your New Relic Ingest License key.
        ingestLicenseKey: 
    # Your New Relic account ID. Custom events representing your test run will be posted to this account.
    accountId: 
    # The geographical region for your New Relic account - US or EU. Default: US
    region: # optional, default is US
    # The path to the JUnit output file.
    testOutputPath: 
    # Any custom attributes to include in JSON format.
    customAttributes: # optional
          
